//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTrans.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class BiddingProfile
    {
        public BiddingProfile()
        {
            this.biddingDetails = new HashSet<BiddingDetails>();
        }
    
        public long biddingid { get; set; }
        public long dtlpostingid { get; set; }
        public long postingid { get; set; }
        public long userid { get; set; }
        public decimal amount { get; set; }
        public string biddercomment { get; set; }
        public short status { get; set; }
        public decimal servicecharges { get; set; }
        public Nullable<short> paymentmethod { get; set; }
        public Nullable<short> rating { get; set; }
        public string cancellationreson { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<System.DateTime> modifydate { get; set; }
    
        public  ICollection<BiddingDetails> biddingDetails { get; set; }
    }
}
