//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTrans.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public  class BiddingProfile
    {
        public BiddingProfile()
        {
            this.biddingDetails = new HashSet<BiddingDetails>();
        }
    
        public long biddingid { get; set; }
        public long dtlpostingid { get; set; }
        public long postingid { get; set; }
        public long userid { get; set; }

        [RegularExpression(Constants.RegexStringInput, ErrorMessage = Constants.StringNumeric)]
        [DisplayName("Amount")]        
        public decimal amount { get; set; }

        [DisplayName("Comment")]
        [StringLength(400)]
        public string biddercomment { get; set; }

        [DisplayName("Status")]
        public short status { get; set; }

        [RegularExpression(Constants.RegexStringInput, ErrorMessage = Constants.StringNumeric)]
        [DisplayName("Service Charges")]
        public decimal servicecharges { get; set; }
        public Nullable<short> paymentmethod { get; set; }

        [RegularExpression(Constants.RegexStringInput, ErrorMessage = Constants.StringNumeric)]
        [DisplayName("Rating")]
        public Nullable<short> rating { get; set; }

        [DisplayName("Cancellation Reason")]
        [StringLength(200)]
        public string cancellationreason { get; set; }

        [DisplayName("Bidding Date")]
        [DisplayFormat(DataFormatString = Constants.FormatDateTime)]
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<System.DateTime> modifydate { get; set; }
        [DisplayName("Last modify date")]
        [DisplayFormat(ApplyFormatInEditMode = false, DataFormatString = Constants.FormatDateTime)]
        public Nullable<System.DateTime> LastModifyDate { get { return modifydate == null ? createddate : modifydate; } }

        public ICollection<BiddingDetails> biddingDetails { get; set; }


        public string posttype { get; set; }
        public string Src_city { get; set; }
        public string Dst_city { get; set; }
        public DateTime biddingactivatedatetime { get; set; }
        public DateTime biddingclosedatetime { get; set; }



        public decimal MaxBidAmount { get; set; }
        public decimal MinBidAmount { get; set; }
        public decimal AvgBidAmount { get; set; }
        public int TotalBids { get; set; }

        public Nullable<short> RatingStatus { get; set; }
   
    }
}
