//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTrans.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public  class BiddingProfile
    {
        public BiddingProfile()
        {
            this.biddingDetails = new HashSet<BiddingDetails>();
        }
    
        public long biddingid { get; set; }
        public long dtlpostingid { get; set; }
        public long postingid { get; set; }
        public long userid { get; set; }

        [RegularExpression(Constants.RegexStringInput, ErrorMessage = Constants.StringNumeric)]
        [DisplayName("Amount")]        
        public decimal amount { get; set; }

        [DisplayName("Comment")]
        [StringLength(400)]
        public string biddercomment { get; set; }

        [DisplayName("Status")]
        public short status { get; set; }

        [RegularExpression(Constants.RegexStringInput, ErrorMessage = Constants.StringNumeric)]
        [DisplayName("Service Charges")]
        public decimal servicecharges { get; set; }
        public Nullable<short> paymentmethod { get; set; }

        [RegularExpression(Constants.RegexStringInput, ErrorMessage = Constants.StringNumeric)]
        [DisplayName("Rating")]
        public Nullable<short> rating { get; set; }

        [DisplayName("Cancellation Reason")]
        [StringLength(200)]
        public string cancellationreason { get; set; }

        [DisplayName("Bidding Date")]
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<System.DateTime> modifydate { get; set; }
    
        public  ICollection<BiddingDetails> biddingDetails { get; set; }
    }
}
