//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTrans.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class InsuranceDetails
    {
        public long insuranceid { get; set; }
        public string insurancename { get; set; }
        public string insurancenumber { get; set; }
        public string companyname { get; set; }
        public string description { get; set; }
        public System.DateTime insurancedate { get; set; }
        public Nullable<System.DateTime> expiredate { get; set; }
        public long vehicleid { get; set; }
        public System.DateTime createddate { get; set; }
        public Nullable<System.DateTime> modifydate { get; set; }
    
        public virtual Vehicle tblmstvehicle { get; set; }
    }
}
