//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTrans.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public  class PackageType
    {
        public PackageType()
        {
        }
    
        public short packagetypeid { get; set; }

        [RegularExpression(Constants.RegexStringInput, ErrorMessage = Constants.StringAlphNumeric)]
        [Required(ErrorMessage = "The Package Type is required")]
        [DisplayName("Package Type")]
        [StringLength(20)]
        public string packagetype { get; set; }

        [DisplayName("Description")]
        [StringLength(200)]
        public string description { get; set; }
    
    }
}
