//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTrans.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public  class PostingPhotos
    {
        public PostingPhotos()
        {
        }

        public long postingdocumentsid { get; set; } = 0;
        public long postingid { get; set; } = 0;
        public long userid { get; set; } = 0;
        public bool isdefault { get; set; } = false;
        public string postingdocument { get; set; }
    }
}
