//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTrans.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public  class PostingProfile
    {
        public PostingProfile()
        {
        }
    
        public long postingid { get; set; }
        [RegularExpression(Constants.RegexStringInput, ErrorMessage = Constants.StringNumeric)]
        [DisplayName("Post Type")]
        [StringLength(10)]
        public string posttype { get; set; }
        public long userid { get; set; }
        [RegularExpression(Constants.RegexStringInput, ErrorMessage = Constants.StringNumeric)]
        [DisplayName("Source Address")]
        [StringLength(200)]
        public string soureaddress { get; set; }
        [RegularExpression(Constants.RegexStringInput, ErrorMessage = Constants.StringNumeric)]
        [DisplayName("Destination Address")]
        [StringLength(200)]
        public string destinationadress { get; set; }

        [RegularExpression(Constants.RegexIntInput, ErrorMessage = Constants.StringNumeric)]
        [DisplayName("Material Type")]
        public short materialtypeid { get; set; }
        [RegularExpression(Constants.RegexStringInput, ErrorMessage = Constants.StringAlphNumeric)]
        [DisplayName("Material Description")]
        [StringLength(200)]
        public string description { get; set; }

        [RegularExpression(Constants.RegexStringInput, ErrorMessage = Constants.StringNumeric)]
        [DisplayName("Package Type")]
        public short packagetypeid { get; set; }
        [RegularExpression(Constants.RegexStringInput, ErrorMessage = Constants.StringAlphNumeric)]
        [DisplayName("Package Description")]
        [StringLength(200)]
        public string packagetypedesc { get; set; }
        public System.DateTime createddate { get; set; }
        public Nullable<System.DateTime> modifydate { get; set; }
    
        public virtual ICollection<PostingDetails> tbldtlpostings { get; set; }

        [RegularExpression(Constants.RegexStringInput, ErrorMessage = Constants.StringAlphNumeric)]
        [DisplayName("State")]
        [StringLength(20)]
        public string src_state { get; set; }
        [RegularExpression(Constants.RegexStringInput, ErrorMessage = Constants.StringAlphNumeric)]
        [DisplayName("City")]
        [StringLength(20)]
        public string src_city { get; set; }
        [RegularExpression(Constants.RegexStringInput, ErrorMessage = Constants.RegexIntInput)]
        [DisplayName("Pincode")]
        public int src_pincode { get; set; }
        [RegularExpression(Constants.RegexStringInput, ErrorMessage = Constants.StringAlphNumeric)]
        [DisplayName("LandMark")]
        [StringLength(30)]
        public string src_landmark { get; set; }

        [RegularExpression(Constants.RegexStringInput, ErrorMessage = Constants.StringAlphNumeric)]
        [DisplayName("State")]
        [StringLength(20)]
        public string dst_state { get; set; }
        [RegularExpression(Constants.RegexStringInput, ErrorMessage = Constants.StringAlphNumeric)]
        [DisplayName("City")]
        [StringLength(20)]
        public string dst_city { get; set; }
        [RegularExpression(Constants.RegexStringInput, ErrorMessage = Constants.RegexIntInput)]
        [DisplayName("Pincode")]
        public int dst_pincode { get; set; }
        [RegularExpression(Constants.RegexStringInput, ErrorMessage = Constants.StringAlphNumeric)]
        [DisplayName("LandMark")]
        [StringLength(20)]
        public string dst_landmark { get; set; }
    }
}
