//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTrans.Models
{
    using System;
    using System.Collections.Generic;
    
    public class UserDetails
    {
        public long dtluserid { get; set; }
        public long userid { get; set; }
        public long companyid { get; set; }
        public short transporttypeid { get; set; }
        public DateTime createddate { get; set; }
        public Nullable<DateTime> modifydate { get; set; }
    
    }
}
