//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTrans.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class Vehicle
    {
        public Vehicle()
        {
        }
    
        public long vehicleid { get; set; }
        public string vehicletype { get; set; }
        public string manufacturername { get; set; }
        public string descrition { get; set; }
        public System.DateTime manufactureryear { get; set; }
        public short totalwheel { get; set; }
        public int weightcapacity { get; set; }
        public string rcbookcopypath { get; set; }
        public string rtoregistrationnumber { get; set; }
        public long companyid { get; set; }
        public System.DateTime registrationdate { get; set; }
        public System.DateTime createddate { get; set; }
        public Nullable<System.DateTime> modifydate { get; set; }
        public long userid { get; set; }
    }
}
