//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTrans.WebPortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public  class Company
    {
        public Company()
        {
        }
    
        public long companyid { get; set; }

        [DisplayName("Company Name")]
        public string companyname { get; set; }

        [DisplayName("Address")]
        public string address { get; set; }

        [DisplayName("Office Tel.No.")]
        public string telenumber { get; set; }

        [DisplayName("Alternet Tel.No.")]
        public string alternettelnumber { get; set; }

        [DisplayName("Country")]
        public string country { get; set; }

        [DisplayName("State")]
        public string state { get; set; }

        [DisplayName("City")]
        public string city { get; set; }
        public long userid { get; set; }

        [DisplayName("Company Type")]
        public int companytype { get; set; }

        [DisplayName("Creation Date")]
        public System.DateTime createddate { get; set; }

        [DisplayName("Last updated Date")]
        public Nullable<System.DateTime> modifydate { get; set; }
    }
}
