//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTrans.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class PostingProfile
    {
        public PostingProfile()
        {
        }
    
        public long postingid { get; set; }
        public string posttype { get; set; }
        public long userid { get; set; }
        public string soureaddress { get; set; }
        public string destinationadress { get; set; }
        public short materialtypeid { get; set; }
        public string description { get; set; }
        public short packagetypeid { get; set; }
        public string packagetypedesc { get; set; }
        public System.DateTime createddate { get; set; }
        public Nullable<System.DateTime> modifydate { get; set; }
    
        public virtual ICollection<PostingDetails> tbldtlpostings { get; set; }
    }
}
