//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTrans.WebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class PackageType
    {
        public PackageType()
        {
        }
    
        public short packagetypeid { get; set; }
        public string packagetype { get; set; }
        public string description { get; set; }
    
    }
}
